version: "3.9"

services:
  api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: >
      bash -lc "pip install --no-cache-dir -r requirements.txt &&
                uvicorn app:app --host 0.0.0.0 --port 8000 --reload"

