# ============================================================
# CI WORKFLOW
# ------------------------------------------------------------
# This workflow runs on every Pull Request and push to `main`.
# It ensures code quality and reliability by:
#   - Installing dependencies
#   - Linting with Ruff
#   - Checking formatting with Black
#   - Running all Pytest unit tests with coverage
# If any step fails, the build fails.
# ============================================================

name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          # Ensure core dev tools are present even if not listed
          pip install -q ruff==0.6.9 black==24.8.0 pytest pytest-cov httpx

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (format check)
        run: black --check --line-length=100 .

      - name: Run tests
        run: pytest -q --disable-warnings --maxfail=1 --cov=. --cov-report=term-missing
