# ============================================================
# PUBLISH WORKFLOW
# ------------------------------------------------------------
# This workflow builds and pushes versioned Docker images
# to GitHub Container Registry (GHCR).
# It runs when:
#   - A push is made to `main` (builds :latest and :<sha> tags)
#   - A version tag is created (e.g., v0.3 -> :v0.3 tag)
# ============================================================

name: Publish Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]   # e.g., v0.1, v0.2.3

permissions:
  contents: read
  packages: write

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push (latest + sha)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Tag & push semver (on v* tags)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          docker pull "$IMAGE:latest"
          docker tag "$IMAGE:latest" "$IMAGE:$VERSION"
          docker push "$IMAGE:$VERSION"
